name: Wire Messenger
description: 'Send messages to Wire conversations'
branding:
  icon: message-circle
  color: white
inputs:
  email:
    description: 'Email of Wire user'
    required: true
    default: ''
  password:
    description: 'Password of Wire user'
    required: true
    default: ''
  conversation:
    description: 'Conversation UUID'
    required: true
    default: ''
  text:
    description: 'Message you want to send'
    required: true
    default: 'Hello, world!'
runs:
  using: 'node12'
  main: 'index.js'
